package net.runelite.client.plugins.xo.blastfurnace;

public enum State {
    NONE,
    COLLECT_BARS,
    DEPOSIT_INVENTORY,
    WITHDRAW_GOLDSMITH_GAUNTLETS,
    EQUIP_GOLDSMITH_GAUNTLETS,
    WITHDRAW_ICE_GLOVES,
    EQUIP_ICE_GLOVES,
    WITHDRAW_ORE,
    PUT_ON_CONVEYOR_BELT,
    OPEN_BANK,
    WAIT_AT_FURNACE,
    WITHDRAW_STAMINA,
    CONSUME_STAMINA,
    DEPOSIT_STAMINA;
}
